### ISSUE TITLE
Add-in automatic public key search

### ISSUE THREAD

**Issue by carlbg** [gpgmailencrypt/gpgmailencrypt#1]
Not really an issue, more of a "feature request". Is it possible to add a module to automatically search and import a public key if it's not found locally?

**Comment by gpgmailencrypt** [comment]
It's implemented for smime keys but not yet for pgp keys. I'll put it on
my todo list

Horst


Am 04.04.2017 um 18:29 schrieb carlbg:

**Comment by gpgmailencrypt** [comment]
feature for gpg keys is now implemented. The public key will be stored in a directory (can be configured in /etc/gpgmailencrypt.conf). To add the keys to the keyring either do it manually or via cron.
