### ISSUE TITLE
Recipient search is case sensitive, results in unencrypted e-mails

### ISSUE THREAD

**Issue by carlbg** [gpgmailencrypt/gpgmailencrypt#2]
When trying to send an email to "example@domain.com", after making sure a public key exists in the local keyring, if I send an e-mail to "Example@domain.com" or "EXAMPLE@domain.com", both instances result in public key not found and unencrypted mail is sent. Sending an e-mail to the lower case "example@domain.com", as listed in the local key ring list, results in encryption without any other change.

Issue replicated on Thunderbird, K-9 mail client, K-@ mail client.

**Comment by gpgmailencrypt** [comment]
Bug fixed
