### ISSUE TITLE
Feature Request: Force Encryption

### ISSUE THREAD

**Issue by carlbg** [gpgmailencrypt/gpgmailencrypt#3]
In the default behavior, a method of encryption is selected (let's say, PGPINLINE). If this method doesn't work (usually no public key found), backup encryption is processed by PDFEncryption. 

However, client's can't decrypt those messages and the user has no idea his PGPInline encryption wasn't successful. Additionally, in the event PDFEncryption doesn't work, clear text e-mail is being sent out without any warning to the internal user. 

In the interest of security, would it be possible to strictly enforce a method of encryption (PGPInline, PGPMime, SMime) or bounce the e-mail back?

**Comment by gpgmailencrypt** [comment]
Bouncing emails in gpgmailencrypt isn't implemented (yet).

But it is possible to redirect unencrypted emails to a second smtp
server (With the config option "useserver2 = True" ). From there you
have the possibility to do whatever you want with these unencrypted emails.


Am 12.04.2017 um 19:00 schrieb carlbg:

**Comment by carlbg** [comment]
Right, ideally I'd rather not have two servers for them to do each part of the job but I'd assume the server2 would forward all mail to a catchall, and then have a procmail rule to return the mail to senders?

Seperate question but along the same lines, currently since all outgoing e-mail is encrypted on the server, and not on the client, all stored emails in "Sent" are stored as clear text. Is the only solution to disable having a copy of emails saved as Sent, or could an encrypted copy be placed in the Sent folder?

**Comment by gpgmailencrypt** [comment]
How to encrypt the "Sent" emails is described in chapter 7.1 of the
documentation

Am 12.04.2017 um 20:58 schrieb carlbg:

**Comment by gpgmailencrypt** [comment]
I'll put it on my todo list

**Comment by gpgmailencrypt** [comment]
implemented
